### ISSUE TITLE
2MB image for a header does not look worth the price

### ISSUE THREAD

**Issue by davidbgk** [etalab/template.data.gouv.fr#17]
https://github.com/etalab/template.data.gouv.fr/blob/master/images/background.jpg could be reduced at least by 4, or even a CSS gradient is enough?!

**Comment by oncletom** [comment]
@thimy ou @Flightan, vous avez utilisé quoi comme couleurs de départ/arrivée pour générer les dégradés ? Si c'est un _placeholder_, on pourrait les exprimer avec les background multiples, genre :

```scss
.hero {
  background: linear-gradient(to bottom, #74e3ec, #c7ffe2),
                        radial-gradient(bottom left, #ff4800, rgba(#f8ffc7, 0%)),
                        radial-gradient(right, #0015ff, rgba(#0015ff, 0%));
}
```

(pas testé le résultat avec les couleurs indiquées)
